# Generated by Django 3.2.12 on 2024-10-14 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BachatGat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BachatGat.mybasemodel')),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=100)),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            bases=('BachatGat.mybasemodel',),
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BachatGat.mybasemodel')),
                ('user_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('government_pro', models.CharField(max_length=255)),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bank_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BachatGat.bankdetail')),
            ],
            bases=('BachatGat.mybasemodel',),
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BachatGat.mybasemodel')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_of_contribution', models.DateField(auto_now_add=True)),
                ('fine', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BachatGat.memberregistration')),
            ],
            bases=('BachatGat.mybasemodel',),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BachatGat.mybasemodel')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('repayment_schedule', models.CharField(max_length=255)),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('loan_status', models.CharField(max_length=50)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BachatGat.memberregistration')),
            ],
            bases=('BachatGat.mybasemodel',),
        ),
        migrations.CreateModel(
            name='FundDistribution',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BachatGat.mybasemodel')),
                ('emergency_fund', models.DecimalField(decimal_places=2, max_digits=12)),
                ('event_fund', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inverstment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bachatgat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BachatGat.bachatgatregistration')),
            ],
            bases=('BachatGat.mybasemodel',),
        ),
    ]
