# Generated by Django 3.2.12 on 2024-10-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BachatGat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='savings',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee')], default='USD', max_length=3),
        ),
    ]
