# Generated by Django 3.2.12 on 2024-10-14 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BachatGat', '0002_bankdetail_funddistribution_loan_savings_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='bank_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='pincode',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funddistribution',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='loan',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='savings',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee')], default='USD', max_length=3),
        ),
    ]
